CLAPP_PATH:=$(dir $(lastword $(MAKEFILE_LIST)))
INCLUDE+=$(CLAPP_PATH)include
DEPEND_LIBS+=$(CLAPP_PATH)dist/$(PLATFORM)/$(BUILD)/$(LIB_PREFIX)CLCommon$(LIB_SUFFIX)

# CL 1.2
#MACROS+=__CL_ENABLE_EXCEPTIONS
#MACROS+=__CL_OVERRIDE_ERROR_STRINGS
# CL 2.0
MACROS+=CL_HPP_TARGET_OPENCL_VERSION=200
MACROS+=CL_HPP_ENABLE_EXCEPTIONS
LDFLAGS_osx+=-framework OpenCL
LIBS_linux+=OpenCL
