CLAPP_PATH:=$(dir $(lastword $(MAKEFILE_LIST)))

MACROS+=__CL_ENABLE_EXCEPTIONS
MACROS+=__CL_OVERRIDE_ERROR_STRINGS
INCLUDE+=$(CLAPP_PATH)include
DYNAMIC_LIBS+=$(CLAPP_PATH)dist/$(PLATFORM)/$(BUILD)/libCLCommon.dylib
LDFLAGS_osx+=-framework OpenCL

